apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ezx8xzoud-nodejs 
  janus-idp.io/tekton: ezx8xzoud-nodejs
  backstage.io/kubernetes-id: ezx8xzoud-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ezx8xzoud-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml